version: '3'
services:
  frontend:
    build: './frontend'
    volumes:
      - './frontend/src:/app/src'
      - './frontend/public:/app/public'
    ports:
      - '3000:3000'
  backend:
    build: './backend'
    volumes:
      - 'backend_db:/backend/data'
    ports:
      - '8080:8080'
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
      - "8443:8443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
      - './demo.key:/etc/ssl/certs/demo.key:ro'
      - './demo.crt:/etc/ssl/certs/demo.crt:ro'
volumes:
  backend_db:
