
version: '3'
services:
  frontend:
    build: './frontend'
    volumes:
      - './frontend:/app'
    ports:
      - '3000:3000'
  backend:
    build: './backend'
    volumes:
      - './backend:/app'
    ports:
      - '8080:8080'
