version: '3'
services:
  frontend:
    build: './frontend'
    volumes:
      - './frontend/src:/app/src'
      - './frontend/public:/app/public'
    ports:
      - '3000:3000'
  backend:
    build: './backend'
    volumes:
      - 'backend_db:/backend/data'
    ports:
      - '8080:8080'
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf:ro'
volumes:
  backend_db:
