openapi: 3.0.3
info:
  title: Collaborative Whiteboard
  description: |-
    A collaborative whiteboard is a shared digital whiteboard that allows multiple users to draw, write, and erase content in real-time. 
    This API allows you to manage the whiteboard and its content.
paths:
  /:
    get:
      tags:
        - board
      summary: Get the current state of the whiteboard
      description: Get the current state of the whiteboard
      operationId: getBoard
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    example: 123e4567-e89b-12d3-a456-426614174000
                  content:
                    type: string
                    example: '{"objects":[{"type":"line","x1":10,"y1":10,"x2":100,"y2":100,"color":"#000000","width":2}]}'
        '400':
          description: Invalid input
  /boards/{boardId}:
    get:
      tags:
        - board
      summary: Get the current state of the whiteboard
      description: Get the current state of the whiteboard
      operationId: getBoard
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    example: 123e4567-e89b-12d3-a456-426614174000
                  content:
                    type: string
                    example: '{"objects":[{"type":"line","x1":10,"y1":10,"x2":100,"y2":100,"color":"#000000","width":2}]}'
        '400':
          description: Invalid input
  /image:
    post:
      tags:
        - board
      summary: Update the content of the whiteboard
      description: Update the content of the whiteboard
      operationId: updateBoard
      requestBody:
        description: The new content of the whiteboard
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  example: '{"objects":[{"type":"line","x1":10,"y1":10,"x2":100,"y2":100,"color":"#000000","width":2}]}'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    example: 123e4567-e89b-12d3-a456-426614174000
                  content:
                    type: string
                    example: '{"objects":[{"type":"line","x1":10,"y1":10,"x2":100,"y2":100,"color":"#000000","width":2}]}'
        '400':
          description: Invalid input
    get:
      tags:
        - board
      summary: Get the current state of the whiteboard
      description: Get the current state of the whiteboard
      operationId: getBoard
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    example: 123e4567-e89b-12d3-a456-426614174000
                  content:
                    type: string
                    example: '{"objects":[{"type":"line","x1":10,"y1":10,"x2":100,"y2":100,"color":"#000000","width":2}]}'
        '400':
          description: Invalid input